# Generated by Django 3.1.3 on 2020-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Фамилия')),
                ('patro_name', models.CharField(default='', max_length=255, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ManyToManyField(to='api.Author')),
            ],
        ),
    ]
