# Generated by Django 3.1.3 on 2020-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201130_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=255, verbose_name='Номер')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(to='api.Chapter'),
        ),
    ]
