# Generated by Django 3.1.3 on 2020-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201208_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.CharField(default='', max_length=25, verbose_name='Номер'),
        ),
    ]
