# Generated by Django 3.1.3 on 2020-12-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201211_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Book',
            new_name='book',
        ),
    ]
