# Generated by Django 3.1.3 on 2020-12-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201211_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
